#ifndef __GAMMER_SYMBOL
#define __GAMMER_SYMBOL

#include <string>

using namespace std;

enum GrammarSymbolType
{
    TERMINAL,
    NON_TERMINAL
};

enum NonTerminal
{
    PROGRAM,
    STATEMENT,
    EXPRESSION,
    BINARY_EXPRESSION,
    UNARY_EXPRESSION,
    PRIMARY_EXPRESSION,
    LITERAL_EXPRESSION,
    IDENTIFIER_EXPRESSION,
    PARENTHESIZED_EXPRESSION,
    ASSIGNMENT_EXPRESSION,
    CALL_EXPRESSION,
    ARGUMENT_LIST,
    IF_STATEMENT,
    WHILE_STATEMENT,
    FOR_STATEMENT,
    FUNCTION_DECLARATION,
    RETURN_STATEMENT,
    VARIABLE_DECLARATION,
    TYPE,
    BLOCK,
    STATEMENT_LIST,
    EXPRESSION_STATEMENT,
    EMPTY_STATEMENT,
    NON_TERMINAL_COUNT
};

string nonTerminalToString(NonTerminal kind);

#endif